### ISSUE TITLE
Add possibility to use in form generator

### ISSUE THREAD

**Issue by WebDucer** [heimrichhannot/contao-multifileupload-bundle#1]
It would be nice to be able to use the multi upload widget also in form generator.

**Comment by janmarkuslanger** [comment]
+1

**Comment by Xirdion** [comment]
I think the `dca`-folder is missing.
In this folder there could be the instructions to show the fields in the form-generator.

**Comment by fatcrobat** [comment]
Started implementation in 1.1.4 but need some more testing.

**Comment by janmarkuslanger** [comment]
@fatcrobat Is the feature implemented now? Is it posible to help?

**Comment by koertho** [comment]
Hi, is this still a relevant feature request? We don't work with form generator, so if someone want to make this bundle compatible, you're welcome!
