### ISSUE TITLE
Use Field in Notification Center

### ISSUE THREAD

**Issue by SGehle** [heimrichhannot/contao-multifileupload-bundle#15]
**Context**
Contao version: 4.9.9
Bundle version: 1.3.2
PHP version: 7.2

**Description**
Its not possible to attache the files that were uploaded to a notification center notification by using the ##form_fieldname##'' simpleToken in the field "attachments via tokens".

**Comment by koertho** [comment]
What means "not possible"? Is there an error? Or is the token just empty? Where do you upload your files (form generator or something other)?

**Comment by SGehle** [comment]
I used it in the form generator - the files will not be added. I think because the return value is the uuid, not the path of the file(s).

**Comment by koertho** [comment]
@SGehle I just looked a while into it and tried, but this is not an easy to solve problem and will take a while. I can't promise you a soon solution, as we don't use the form generator and so this is not a priority functionality for us.

**Comment by SGehle** [comment]
@koertho - Okay. I hope to find a solution to make a pull request.

**Comment by koertho** [comment]
@SGehle That would be great. You can have a look into my pull request as starting point: #16

**Comment by federleicht** [comment]
Hello koertho, I would also need the function. Would be great if the files could be attached via tokens. Thank you.

**Comment by koertho** [comment]
We added form generator support in version 1.7. Maybe this already fixes the issue for you.
