### ISSUE TITLE
missing translations

### ISSUE THREAD

**Issue by Xirdion** [heimrichhannot/contao-multifileupload-bundle#3]
There is already the possibility to choose this type of field in the form-generator. But no translations are given so that the name in the selection-field is empty.
Missing translation for `$GLOBALS['TL_LANG']['FFL']['multifileupload']`.

**Comment by rorych** [comment]
+1

Something like this would be great:
`$GLOBALS['TL_LANG']['FFL']['multifileupload'] = array('Datei-Upload (Multiple)');`
