### ISSUE TITLE
can upload only one file at a time, not several

### ISSUE THREAD

**Issue by cmette** [heimrichhannot/contao-multifileupload-bundle#33]
**Context**
Contao version: **4.9.22**
Bundle version: **1.5.0**
PHP version: **7.4.11**
DEV ENV: **Windows 10x64 with laragon** and in the same way **ubuntu server**

**Description**
the bundle only allows uploading a single file, if another one is uploaded then the error message: 'You cannot upload more files' appears. Multiple files cannot be uploaded together. 

our DCA Snippet look like this:
```
'attachments_common' => [
            'exclude' => true,
            'inputType' => 'multifileupload',
            'eval' => [
                'tl_class' => 'clr',
                'extensions' => 'docx,pdf,ppt', //Config::get('validImageTypes'),
                'filesOnly' => true,
                'maxFiles' => 100,
                'fieldType' => 'radio',
                'maxUploadSize' => '1M',
                'uploadFolder' => 'files/DATA-PLACEHOLDER',
                'addRemoveLinks' => true,
                'minImageWidth' => '600px',
                'minImageHeight' => '300px',
                'maxImageWidth' => '1600px',
                'maxImageHeight' => '1200px',
                'multipleFiles' => true,
                'labels' => [
                    'head' => $GLOBALS['TL_LANG']['tl_table']['attachments_common_label_head'],
                    'body' => $GLOBALS['TL_LANG']['tl_table']['attachments_common_label_body'],
                ],
                'skipDeleteAfterSubmit' => true,
            ],
            'uploadPathCallback' => [['tl_table', 'uploadPathCallback']],
            //'validateUploadCallback' => [['tl_table', 'validateUploadCallback']],
            'sql' => 'blob NULL',
],
```

**Comment by cmartin6** [comment]
I get the same error...

**Comment by koertho** [comment]
@cmette @cmartin6 I assume you use it as backend widget?

**Comment by cmette** [comment]
Sure. This page https://github.com/heimrichhannot/contao-multifileupload-bundle shows an example with a backend edit page and a DCA snippet for the backend... there to read: _Contao **front end widget** that provides dropzonejs.com functionality **to both back and front end**._ What does it mean?

**Comment by koertho** [comment]
@cmette @cmartin6 Ok, I found the issue. The multipleFiles option is completely ignores, the fieldType option is the option you need. Just set it to checkbox and you can upload multiple files.  I will update the readme. Sorry for this inconvenience!

**Comment by koertho** [comment]
The widget can be used in the frontend, but as far as I know only with formhybrid.

**Comment by cmette** [comment]
Thanks! I will test it as soon as possible.

**Comment by koertho** [comment]
I just updated the readme. Please write if you're missing something or run into other trouble :)
