### ISSUE TITLE
Speicherziel liegt außerhalb des Contao-Upload-Verzeichnisses.

### ISSUE THREAD

**Issue by exscorp** [heimrichhannot/contao-multifileupload-bundle#47]
Hallo, frische Contao 4.13.12 Installation + dev-master der Extension (brauche das multiupload im Formulargenerator).

Beim Upload bekomme ich immer diesen Fehler "**Speicherziel liegt außerhalb des Contao-Upload-Verzeichnisses.**"

Ist es ein Fehler in der Extension (weil noch kein release) oder liegt es an meiner Installation (local / laragon).

![Screenshot 2022-11-03 183919](https://user-images.githubusercontent.com/3008649/199797599-5bd79c3d-fc62-4623-9286-ca3bfb038c5f.png)

**Comment by koertho** [comment]
Ui, da hatte ich vergessen zu taggen. Kannst jetzt Version 1.7 nehmen, ist aber der gleiche Stand wie dev-master.
Hast du nen Symlink oder so drin? Ich habe es ehrlich gesagt nur unter 4.9 getestet, ich schaue nochmal. Aber eigentlich sollte sich da nichts geändert haben.

**Comment by exscorp** [comment]
Scheint ein lokales Problem zu sein. Habe es gerade auf einem Liveserver (4.9 und 4.13) probiert und dort kommt dieser Fehler nicht. Kannst den issue dann eigentlich schließen :)

Könntest du mir eventuell helfen woran es liegen kann, den ich nutze lokal Laragon seit Jahren und hatte noch nie Probleme. Wüsste auch nicht das Symlinks gesetzt wären oder so.

Eine Sache die mir beim Testen gerade aufgefallen ist: In der Mail bekomme ich: 

- beim multiupload für die Datei die "UUID" > `���\�Z>�D` 
- beim normalen Datei-Upload bekomme ich den Pfad/URL zu der Datei >`…/files/dl2/testbild-1.jpg`

Kann man das irgendwie Einstellen das dort auch die URL ausgegeben wird?

**Comment by koertho** [comment]
Puh, kenne Laragon nicht, keine Ahnung wie das intern arbeitet. Du könntest per Kommandozeile den echten Pfad herausbekommen, wenn du in den entsprechenden Ordner gehst und dort `realpath .` ausführst.

Ja, das kann daran liegen, dass die Uploadfunktion von Contao anders ist und daher die Mechanismen zum Umwandeln des Pfades nicht greifen. Mach gerne ein neues Issue dazu auf, werde ich sicher irgendwann sowieso angehen müssen. Bis dahin kannst du die Pfade auch im `sendNotificationMessage` hook "übersetzen", falls du notification center nutzt, sonst geht es sicher auch in einem der form generator hooks, vermute der validate hook dürfte passen.

**Comment by exscorp** [comment]
Beim `realpath .` zeigt er mir immer den gleichen Pfad an außer das die slashes anders sind (Windowssystem)

```
C:\laragon\www\upload
λ realpath .
/c/laragon/www/upload
```

```
C:\laragon\www\upload\files
λ realpath .
/c/laragon/www/upload/files
```

```
C:\laragon\www\upload\files\dl
λ realpath .
/c/laragon/www/upload/files/dl
```


Mit den hooks habe ich mich noch nicht beschäftigt aber mache ein issue dazu auf.

**Comment by koertho** [comment]
Mhm, könnte eventuell wirklich an der Windows-Umgebung liegen. Ich schau mir da nochmal den Code an.

**Comment by exscorp** [comment]
Dies scheint mit #50 behoben zu sein. 
Zumindest bekomme ich diese "**Speicherziel liegt außerhalb des Contao-Upload-Verzeichnisses.**" Fehlermeldung nicht mehr.

**Comment by koertho** [comment]
@exscorp Ich habe ein paar / durch die PHP-Verzeichniss-Trenner-Konstante ersetzt, das könnte der Grund sein :)
