### ISSUE TITLE
URL statt UUID ausgeben

### ISSUE THREAD

**Issue by exscorp** [heimrichhannot/contao-multifileupload-bundle#48]
Beim Formularversand werden in der Mail (Contao-Intern und Notification Center) die Dateien als UUID ausgegeben.

contao-multifileupload-bundle  > `���\���Z�>��D`
Contao nativer Datei-Upload >`…/files/dl/testbild-1.jpg`

Kann man das irgendwie Einstellen das dort auch die URL ausgegeben wird?

**Comment by koertho** [comment]
@exscorp You could try #50 if it works for you.

**Comment by exscorp** [comment]
Funktioniert nicht, das Notification Center Token wird nicht mehr übersetzt, in der Mail kommt nur `##form_upload##` statt dem Wert/File an.

**Comment by exscorp** [comment]
was mir gerade noch aufgefallen ist, die Dateien bekommen einen komischen Namen/ID `mfuidXXX…` an den Dateinamen angehängt. Was natürlich nicht erwünscht ist.

![Screenshot 2022-11-24 201209](https://user-images.githubusercontent.com/3008649/203852586-7d3ef109-44b3-4875-a6d4-b518d466f053.png)

**Comment by koertho** [comment]
@exscorp Es wird auch kein Token form_upload angelegt, weder vom notification center noch vom multifileupload-bundle. Die Dateien sind unter attachment_* tokens verfügbar, wir auch beim "normalen" fileupload.

Die Benennung der Dateien erfolg über Anhang einer unique id, um gleiche dateinamen auszuschließen, das ist bei dem Bundle Standard-Verhalten. Da kann man über Events/Hooks nachträglich noch ändern, bspw über den PostUpload event, welcher den postUpload hook beerbt (habe ich gerade noch mit in den PR eingebaut). Ansonsten ist dies aber ein anderes Thema, welches in ein eigenes Issue gehört.

**Comment by exscorp** [comment]
Das `##form_upload##` ist das von mir angelegte multifileupload im Formular. 

![Screenshot 2022-11-25 104641](https://user-images.githubusercontent.com/3008649/203953925-043e5ff4-f9c4-483d-a78b-a569067428df.png)

Ich möchte ja die Daten als Text/URLs per Mail versenden und nicht als attachment. Wobei das attachment hier auch nicht funktioniert. Beim Versand (mit notification center) kommt nur `##form_upload##` in der Mail an, sonst nichts.

![Screenshot 2022-11-25 104606](https://user-images.githubusercontent.com/3008649/203954072-19db0328-d586-451d-a568-56e910e47375.png)

Wähle ich **Per E-Mail versenden** (Contao Intern) und nicht über **notification center**, dann kommen die Daten als attachment an und auch per Text (hier aber wieder nur die UUID statt URL).

Beim Verwenden des Datei-Upload von Contao und **notification center** kommt der Text als URL und die Datei als attachment an. Es muss also irgendwo noch ein bug bei der Übergabe der Daten von **multifileupload** an **notification center** geben.

**Comment by koertho** [comment]
Schaue bitte einfach mal in der Warteschlange die verfügbaren TOkens an. Der Token-Name beginnt einfahc mit ##attachment_ ..., hat nichts direkt mit Dateianhängen zu tun. Ich habe es versucht genau so abzubilden, wie es contao macht, sollte nun eigentlich funktionieren

**Comment by koertho** [comment]
Ach ja, wir haben hier ja ein "Multifile" -Upload, daher heißen die uploads nicht upload (wenn das Feld upload heißt), sondern upload__0, upload__1 usw., wenn vorhanden.

**Comment by exscorp** [comment]
> Ach ja, wir haben hier ja ein "Multifile" -Upload, daher heißen die uploads nicht upload (wenn das Feld upload heißt), sondern upload__0, upload__1 usw., wenn vorhanden.

Mit __0, __1 usw. hat es sofort funktioniert. Sowohl als Text/URL (leider noch mit der ID dahinter, hier könnte man doch _01, _02 etc. machen) als auch als Attachment. Ist es irgendwo dokumentiert oder wie hätte ich drauf kommen sollen? :D

Kann man das irgendwie vereinfachen oder anders schreiben, den ich weiß ja am Ende nicht wie viele Daten da hochgeladen werden?

**Comment by exscorp** [comment]
Ein "bug" besteht noch. Es werde nicht alle files übergeben.
Lade ich eine Datei hoch, kommt nichts an > nur der simple token.
Lade ich zwei Dateien hoch, kommt nur die erste an.
Bei 5 Daten nur 4 uws. also immer eine Datei weniger.

**Comment by koertho** [comment]
> > Ach ja, wir haben hier ja ein "Multifile" -Upload, daher heißen die uploads nicht upload (wenn das Feld upload heißt), sondern upload__0, upload__1 usw., wenn vorhanden.
> 
> Mit __0, __1 usw. hat es sofort funktioniert. Sowohl als Text/URL (leider noch mit der ID dahinter, hier könnte man doch _01, _02 etc. machen) als auch als Attachment. Ist es irgendwo dokumentiert oder wie hätte ich drauf kommen sollen? :D
> 
> Kann man das irgendwie vereinfachen oder anders schreiben, den ich weiß ja am Ende nicht wie viele Daten da hochgeladen werden?

Wie gesagt, man sieht alle TOkens wenn man eine Testmail per Warteschlange verschickt und sich dann im Backend die Details anschaut.. Generell sind die Tokens im Notification Center eher schlecht dokumentiert. 
Und nein, das ist noch nicht dokumentiert, PR ist willkommen ;) Du kannst auch gerne einen PR für einen Token machen, der alle Bilder enthält ;)

**Comment by koertho** [comment]
> Ein "bug" besteht noch. Es werde nicht alle files übergeben. Lade ich eine Datei hoch, kommt nichts an > nur der simple token. Lade ich zwei Dateien hoch, kommt nur die erste an. Bei 5 Daten nur 4 uws. also immer eine Datei weniger.

Konnten wir noch nicht reproduzieren, bitte neues Issue dazu. Denke daran, das die Datei 0-indexiert sind.

**Comment by exscorp** [comment]
> Konnten wir noch nicht reproduzieren, bitte neues Issue dazu. Denke daran, das die Datei 0-indexiert sind.

Die 0 war es, funktioniert also richtig.
