### ISSUE TITLE
Not working with form generator

### ISSUE THREAD

**Issue by cmartin6** [heimrichhannot/contao-multifileupload-bundle#8]
Would like to use this extension in Contao 4.8 - is there a migration planned?

**Comment by koertho** [comment]
Theoretical this extension is compatible with contao 4.8. Is there something not working?

**Comment by konsultaner** [comment]
I get the following error:

[2020-02-06 14:05:11] request.CRITICAL: Uncaught PHP Exception Exception: "Kein "uploadFolder" für das Feld "" in eval angegeben." at C:\Users\burkh\websites\deinhandwerk4.8\vendor\heimrichhannot\contao-multifileupload-bundle\src\Form\FormMultiFileUpload.php line 71 {"exception":"[object] (Exception(code: 0): Kein \"uploadFolder\" für das Feld \"\" in eval angegeben. at C:\\Users\\burkh\\websites\\deinhandwerk4.8\\vendor\\heimrichhannot\\contao-multifileupload-bundle\\src\\Form\\FormMultiFileUpload.php:71)"} []

**Comment by koertho** [comment]
The error message has nothing to do with contao 4.8, you just forgot to add the upload setting in your dca field config.

**Comment by konsultaner** [comment]
I updated from contao 3.4.x to 4.8. when using the formular generator to edit the formular, I get this error.

**Comment by koertho** [comment]
I don't think this bundle is form generator compatible, since we don't use the form generator and never tested them together, at least not in the last time. There are also no plan to make them compatible, but you are welcome to do a pull request.

**Comment by konsultaner** [comment]
https://github.com/heimrichhannot/contao-multifileupload-bundle/blob/master/src/Form/FormMultiFileUpload.php#L126

Is this the error I am seeing?

**Comment by konsultaner** [comment]
@koertho These 2 changes would make my installation work at least without an error.

**Comment by koertho** [comment]
@Defcon0 Your opinion?

**Comment by Defcon0** [comment]
@konsultaner Does  it work all the way through after this change? Are the files uploaded to system/tmp?

One thing to keep in mind: at least in Contao 4 (not sure if that's the case in Contao 4 still) the system/tmp folder is cleand regularly by Contao. If one would like to store the form submission, the associated file would be gone after some hours.

**Comment by konsultaner** [comment]
@Defcon0 As soon as I upload a file a get a "Wrong token" error. So it looks like it's not going to work just like that. I'll try it out as soon as I have the first form work on contao 4.8.

**Comment by konsultaner** [comment]
@Defcon0 @koertho the wrong token issue prevents it from uploading. It seems like every drop causes the multifileuploader to send the complete from to the server. It seems like the bundles ajax handler is not used?? any idea how to debug it?

**Comment by konsultaner** [comment]
>@konsultaner Does it work all the way through after this change? Are the files uploaded to system/tmp?

this plugin does it exactly like that:
https://packagist.org/packages/terminal42/contao-fineuploader

**Comment by koertho** [comment]
@Defcon0 Hier wäre vielleicht ein Ansatz, einen Fallbackfolder zu definieren (könnte ja per default system/tmp sein) und diesen per config anpassbar zu machen. Dann könnte man je nach Seite sogar auf die definition in der DCA verzichten, falls man nur einen Ordner benötig.

**Comment by Defcon0** [comment]
No problem with defining a fallback folder, but @konsultaner stated that it doesn't work though.

**Comment by koertho** [comment]
The wrong token issue is already reported in another issue (#11) and seems to be related to the form generator or frontend. For form generator I think we need both changes.

**Comment by koertho** [comment]
Form generator is now supported in 1.7.
